config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ## 前台路由
  # root
  root "posts#index"

  # 使用者
  resources :users, only: [:edit, :update, :show] do
    member do
      get :draft
      get :comment
      get :collect
      get :friend

      # 好友關係
      post :friend_request
      post :friend_accept
      post :friend_ignore
    end
  end

  # 文章
  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]

    # 文章收藏記錄
    member do
      post :collect
      delete :uncollect
    end
  end

  # posts#index 的文章分類按鈕
  resources :categories, only: [:show]

  ## 後台路由
  # 進入後台必須有管理員 (admin) 權限
  namespace :admin do
    # GET /admin/users  後台可以瀏覽所有使用者清單
    # POST  /admin/:id/user   可以更新使用者的身份
    resources :users, only: [:index, :update]
    # 後台可以 CRUD `文章的分類` (但不能刪除已經有被使用的分類)
    resources :categories

    # 後台首頁
    root "users#index"
  end

  # API路由
  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, except: [:edit]
    end
  end

  # Feeds
  resources :feeds, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_authentication_token

  # 讓 name 爲必填欄位
  validates_presence_of :name

  # 加上驗證 name 不能重覆
  validates_uniqueness_of :name

  # 刪除使用者時，一併將該使用者的文章刪除
  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  # 使用者有很多收藏文章的記錄
  has_many :collects, dependent: :destroy

  # 使用者有很多在收藏記錄裡的的文章
  has_many :collected_posts, through: :collects, source: :post

  # 好友與好友關係
  has_many :friendships, dependent: :destroy

  # 檢查是否爲網站管理員
  def is_admin?
    if self.role == "Admin"
      return true
    end
  end

  def is_collected?(post)
    self.collected_posts.include?(post)
  end

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

  def friend?(user)
    # 判斷兩方是否有好友邀請記錄
    friendship_record = Friendship.where(user_id: user.id, friend_id: self.id).or(Friendship.where(user_id: self.id, friend_id: user.id))
    if friendship_record.any?
      # 有好友記錄
      if friendship_record.first.status == "accept"
        return "friend"
      else
        return "exist"
      end
    else
      # 沒有好友記錄
      return "none"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])

    # 只更新一個欄位
    @user.update(role: params[:role])
    flash[:notice] = "#{@user.name}'s role has been updated to #{params[:role]}."

    redirect_to admin_users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:friend_accept, :friend_ignore]

  def show
    # set_user

    @posts = @user.posts.where(status: "publish").order(id: :desc)
  end

  def edit
    if current_user == @user
      # allow to edit

    else
      redirect_to user_path(@user.id)
    end
  end

  def update
    # set_user
    if @user.update(user_params)
      flash[:notice] = "User data was successfully updated."
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "User was failed to update!"
      render :edit
    end
  end

  # "My Draft" page
  def draft
    # set_user

    if current_user == @user
      @posts = @user.posts.where(status: "draft").order(id: :desc)
    end
  end

  def comment
    # set_user

    @comments = @user.comments.order(id: :desc)
  end

  def collect
    # set_user

    @collects = @user.collects
  end

  def friend_request
    # set_user

    if current_user != @user
      # 建立好友邀請
      @friend_request = Friendship.new(
        user_id: current_user.id,
        friend_id: @user.id
      )

      @friend_request.save
    end

  end

  def friend_accept
    @friend_request = Friendship.find(params[:id])

    @friend_request.status = "accept"
    @friend_request.save
  end

  def friend_ignore
    @friend_request = Friendship.find(params[:id])

    @friend_request.status = "ignore"
    @friend_request.save
  end

  def friend
    # set_user

    # 來自其他使用者的好友邀請，好友發起人： user_id
    @wait_for_responses = Friendship.where(user_id: @user.id, status: "wait")

    @requests = Friendship.where(friend_id: @user.id, status: "wait")

    @friendships = Friendship.where(user_id: @user.id, status: "accept").or(Friendship.where(friend_id: @user.id, status: "accept"))
  end

  private
  def set_user
    @user = User.find(params[:id])
    return @user
  end

  # for strong parameters
  def user_params
    params.require(:user).permit(:name, :introduction, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/collect.html.erb
<div class="container">
  <br>
  <%= render partial: "shared/user_content" %>

  <br>
  <%= render partial: "shared/user_nav_tabs" %>

  <br>

  <% @collects.each do |collect| %>
    <div class="card" id="collect-post-<%= collect.post.id %>">
      <div class="card-body">
        <h5 class="card-title">
          <div class="row">
            <div class="col-9">
              <%= link_to collect.post.title, post_path(collect.post) %>
            </div>
            <div class="col-3">
              <% if @user == current_user %>
                <% @post = collect.post # for render partial %>
                <%= render partial: "shared/collect_button" %>
              <% end %>
            </div>
          </div>
        </h5>

      </div>
    </div>
  <% end %>
</div>

app/views/users/comment.html.erb
<div class="container">
  <br>
  <%= render partial: "shared/user_content" %>

  <br>
  <%= render partial: "shared/user_nav_tabs" %>

  <br>

  <!-- 回覆過的文章標題語回覆內容列表 -->
  <% @comments.each do |comment| %>
    <div class="">
      <%= link_to comment.post.title, post_path(comment.post.id) %>
    </div>

    <div class="row">
      <div class="col-9 border p-3">
        <%= comment.content %>
      </div>
      <div class="col-3">
        <% @post = comment.post %>
        <%= render partial: "shared/comment_button", locals: {comment: comment} %>
      </div>
    </div>

    <hr>
  <% end %>

</div>

app/views/users/draft.html.erb
<div class="container">
  <br>
  <%= render partial: "shared/user_content" %>

  <br>
  <%= render partial: "shared/user_nav_tabs" %>

  <br>

  <!-- 文章列表 -->
  <%= render partial: "shared/user_post" %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
    <%= @user.errors.full_messages.to_sentence %>
  <% end %>
  <h1>修改個人資料</h1>
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :name, "使用者名稱" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group>
      <%= f.label :introduction, "自我介紹" %>
      <%= f.text_area :introduction, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :avatar, "大頭貼" %><br>
      <%= filestack_image @user.avatar, transform: filestack_transform.resize(width:150, height:150) if @user.avatar && @user.avatar != "" %>
      <%= f.filestack_field :avatar, '選擇你的大頭貼照片',
      pickerOptions: {
        accept: 'image/*',
        fromSources: ['local_file_system', 'url'],
        maxFiles: 1,
        maxSize: 10240000
        } %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <%= link_to "Cancel", user_path(@user.id), class: "btn btn-light" %>
    </div>
  <% end %>
</div>

app/views/users/friend.html.erb
<div class="container">
  <br>
  <%= render partial: "shared/user_content" %>

  <br>
  <%= render partial: "shared/user_nav_tabs" %>

  <br>

  <div class="card">
    <!-- 顯示收到 @user 送出的好友申請並等待回覆的使用者 -->
    <h5 class="card-header text-center">Waiting for response</h5>
    <div class="card-body row">
      <% @wait_for_responses.each do |response| %>
        <% if response.friend.id %>
        <span class="card-text text-center p-1">
          <%= link_to user_path(response.friend.id) do %>
            <%= filestack_image response.friend.avatar, transform: filestack_transform.resize(width:70, height:70) if response.friend.avatar && response.friend.avatar != "" %>
            <h5><%= response.friend.name %></h5>
          <% end %>
        </span>
        <% end %>
      <% end %>
    </div>

    <!-- 顯示發送邀請給 @user 的使用者 -->
    <h5 class="card-header text-center">Friend Request</h5>
    <div class="card-body row">
      <% @requests.each do |request| %>
      <span class="card-text text-center p-1" id="request-<%= request.id %>">
        <%= link_to user_path(request.user) do %>
          <%= filestack_image request.user.avatar, transform: filestack_transform.resize(width:70, height:70) if request.user.avatar && request.user.avatar != "" %>
          <h5><%= request.user.name %></h5>
        <% end %>

        <% if current_user == @user %>
          <%= link_to friend_accept_user_path(request.id), method: :post, class: "btn btn-sm", remote: true do %>
            <%= fa_icon "check-circle 2x" %>
          <% end %>

          <%= link_to  friend_ignore_user_path(request.id), method: :post, class: "btn btn-sm", remote: true do %>
            <%= fa_icon "times-circle 2x" %>
          <% end %>
        <% end %>

      </span>
      <% end %>
    </div>

    <!-- 顯示 @user 的好友清單 -->
    <h5 class="card-header text-center">Friend List</h5>
    <div class="card-body row" id="friend-list">
      <% @friendships.each do |friendship| %>
        <!-- 辨識好友 -->
        <% if @user != friendship.user %>
          <% friend = friendship.user %>
        <% else %>
          <% friend = friendship.friend %>
        <% end %>
        <span class="card-text text-center p-1">
          <%= link_to user_path(friend) do %>
            <%= filestack_image friend.avatar, transform: filestack_transform.resize(width:70, height:70) if friend.avatar && friend.avatar != "" %>
            <h5><%= friend.name %></h5>
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/users/friend_accept.js.erb
// 先把按鈕移除
$("#request-<%= @friend_request.id %>").children(".btn").remove();

// 取出 成爲朋友的使用者資訊
var friend_user = $("#request-<%= @friend_request.id %>");

// 把使用者資訊移動到 Friend List
$("#friend-list").append(friend_user);

app/views/users/friend_ignore.js.erb
$("#request-<%= @friend_request.id %>").remove();

app/views/users/friend_request.js.erb
var unable_button = '<%= j render partial: "shared/friendship_button" %>';

$("#friend-btn-<%= @user.id %>").children().remove();

$("#friend-btn-<%= @user.id %>").html(unable_button);

app/views/users/show.html.erb
<div class="container">
  <br>
  <%= render partial: "shared/user_content" %>

  <br>
  <%= render partial: "shared/user_nav_tabs" %>

  <br>

  <!-- 文章列表 -->
  <%= render partial: "shared/user_post" %>
</div>