config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ## 前台路由
  # root
  root "posts#index"

  # 使用者
  resources :users, only: [:edit, :update, :show] do
    member do
      get :draft
      get :comment
      get :collect
      get :friend

      # 好友關係
      post :friend_request
      post :friend_accept
      post :friend_ignore
    end
  end

  # 文章
  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]

    # 文章收藏記錄
    member do
      post :collect
      delete :uncollect
    end
  end

  # posts#index 的文章分類按鈕
  resources :categories, only: [:show]

  ## 後台路由
  # 進入後台必須有管理員 (admin) 權限
  namespace :admin do
    # GET /admin/users  後台可以瀏覽所有使用者清單
    # POST  /admin/:id/user   可以更新使用者的身份
    resources :users, only: [:index, :update]
    # 後台可以 CRUD `文章的分類` (但不能刪除已經有被使用的分類)
    resources :categories

    # 後台首頁
    root "users#index"
  end

  # API路由
  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, except: [:edit]
    end
  end

  # Feeds
  resources :feeds, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  # 刪除文章時一併刪除 文章的分類記錄
  has_many :categories_posts, :dependent => :destroy

  has_many :categories, through: :categories_posts

  belongs_to :user
  has_many :comments, :dependent => :destroy

  has_many :collects, :dependent => :destroy

  def increase_visit
    self.viewed_count += 1
    save!
  end
end

app/views/shared/_collect_button.html.erb
<% if current_user.is_collected?(@post) %>
  <%= link_to "Uncollect", uncollect_post_path(@post.id), method: :delete, class: "btn btn-outline-info", id: "uncollect-#{@post.id}", remote: true %>
<% else %>
  <%= link_to "Collect", collect_post_path(@post.id), method: :post, class: "btn btn-outline-primary", id: "collect-#{@post.id}", remote: true %>
<% end %>

app/views/shared/_comment_button.html.erb
<% if current_user == comment.user %>
  <%= link_to edit_post_comment_path(@post.id, comment.id), class: "btn btn-info btn-sm" do %>
    <%= fa_icon "edit" %>
  <% end %>
<% end %>

<% if current_user.role == "Admin" || current_user == comment.user %>
  <%= link_to post_comment_path(@post.id, comment.id), method: :delete, data: {disable_with: "waiting.."}, class: "btn btn-danger btn-sm" do %>
    <%= fa_icon "trash" %>
  <% end %>
<% end %>

app/views/shared/_comment_content.html.erb
<!-- 留言者的資料與文章內容 -->
<div class="row border mb-1">
  <div class="col-sm-2 text-center">
    <!-- user.avatar, user.name, add_friend button -->
    <span class="badge badge-pill badge-warning"><%= count.to_s + "樓" %></span>
    <%= link_to user_path(comment.user.id) do %>
      <div class="text-center">
        <%= filestack_image comment.user.avatar, transform: filestack_transform.resize(width:85, height:85), class:"mt-2" if comment.user.avatar %>
        <div>
          <%= comment.user.name %>
        </div>
      </div>
    <% end %>
    <% @user = comment.user %>
    <%= render partial: "shared/friendship_button" %>
  </div>

  <div class="col-sm-10">
    <%= comment.content %>

    <div class="clearfix"></div>
    <div class="float-right">
      <%= render partial: "shared/comment_button", locals: {comment: comment} %>
    </div>
  </div>
</div>

app/views/shared/_friendship_button.html.erb
<% if @user != current_user && @user.friend?(current_user) == "none" %>
  <span id="friend-btn-<%= @user.id %>">
    <%= link_to "Add Friend", friend_request_user_path(@user), method: :post, class: "btn btn-dark btn-sm mb-1", remote: true %>
  </span>
<% elsif @user.friend?(current_user) == "friend" %>
  <span class="badge badge-pill badge-success md-1">Friend</span>
<% elsif @user.friend?(current_user) == "exist" %>
  <button type="button" class="btn btn-secondary btn-sm mb-1" disabled>Add Friend</button>
<% end %>

app/views/shared/_post_button.html.erb
<% if current_user == post.user %>
  <%= link_to edit_post_path(post.id), class: "btn btn-info btn-sm mb-1" do %>
    <%= fa_icon "edit" %>
  <% end %>
<% end %>

<% if current_user.role == "Admin" || current_user == post.user %>
  <%= link_to post_path(post.id), method: :delete, data: {disable_with: "waiting.."}, class: "btn btn-danger btn-sm mb-1" do %>
    <%= fa_icon "trash" %>
  <% end %>
<% end %>

app/views/shared/_post_content.html.erb
<!-- 作者的資料與文章內容 -->
<div class="row border mb-1">
  <div class="col-sm-2">
    <!-- user.avatar, user.name, add_friend button -->
    <div class="text-center">
      <%= link_to user_path(post_object.user.id) do %>
        <%= filestack_image post_object.user.avatar, transform: filestack_transform.resize(width:85, height:85), class:"mt-2" if post_object.user.avatar %>

        <div>
          <%= post_object.user.name %>
        </div>
      <% end %>

      <% @user = post_object.user %>
      <%= render partial: "shared/friendship_button" %>
    </div>

  </div>

  <div class="col-sm-10">
    <br>
    <%= filestack_image(post_object.file, transform: filestack_transform.resize(width:400, height:300), class:"border d-flex justify-content-center") if (post_object.file != "" && post_object.file != nil) %>
    <br>
    <%= post_object.content %>

    <div class="clearfix"></div>
    <div class="float-right">
      <%= render partial: "shared/post_button", locals: {post: post_object} %>
    </div>
  </div>
</div>

app/views/shared/_post_edit.html.erb
<%= form_for @post do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.filestack_field :file, 'File', pickerOptions: { accept: 'image/*', fromSources: ['local_file_system', 'url'], maxFiles: 1, maxSize: 10240000 }, class: "btn btn-info" %>
</div>

<div class="form-group">
  <div class="row">
    <legend class="col-form-label col-sm-2 pt-0">
      Who Can See
    </legend>
    <div class="col-sm-10">
      <div class="form-check form-check-inline">
        <!-- http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormHelper.html#method-i-radio_button -->
        <%# radio_button(object_name, method, tag_value, options = {}) %>
        <%= radio_button :post, :who_can_see, "All", { checked: true , class: "form-check-input" } %>

        <%# label_tag(name = nil, content_or_options = nil, options = nil, &block) %>
        <%= label_tag :post_who_can_see_all, "All", class: "form-check-label" %>
      </div>
      <div class="form-check form-check-inline">
        <%= radio_button :post, :who_can_see, "Friend", {  class: "form-check-input" } %>
        <%= label_tag :post_who_can_see_friend, "Friend", class: "form-check-label" %>
      </div>
      <div class="form-check form-check-inline">
        <%= radio_button :post, :who_can_see, "Myself", {  class: "form-check-input" } %>
        <%= label_tag :post_who_can_see_myself, "Myself", class: "form-check-label" %>
      </div>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <legend class="col-form-label col-sm-2 pt-0">
      Category
    </legend>
    <div class="col-sm-10">
      <%# Category.all.each do |category| %>
        <div class="form-check form-check-inline">
          <%= f.collection_check_boxes :category_ids,  Category.all, :id, :name do |cb| %>
            <div class="m-1">
              <%= cb.check_box class: "form-check-input" %>
              <%= cb.label class: "form-check-label "%>
            </div>
          <% end %>
        </div>
      <%# end %>
    </div>
  </div>
</div>

<div class="form-group">
  Status :
  <br>
  <%# posts controller 用 <input /> 的 value 值 來判斷是發佈文章或存成草稿 %>
  <%= f.submit "Save Draft", class: "btn btn-info" %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <% if @post.errors.any? %>
    <%= @post.errors.full_messages.to_sentence %>
  <% end %>
</div>
<% end %>

app/views/shared/_post_list.html.erb
<!-- 文章分類按鈕 -->
<ul class="nav nav-pills">
  <li class="nav-item">
    <%= link_to "All", root_path, class:"btn btn-light  nav-link #{ 'active' if current_page?(root_path)}" %>
  </li>
  <% @categories.each do |category| %>
  <li class="nav-item">
    <%= link_to category.name, category_path(category.id), class:"btn btn-light nav-link #{ 'active' if current_page?(category_path(category.id)) }" %>
  </li>
  <% end %>
</ul>

<br>

<!-- 文章列表 -->
<table class="table table-dark table-striped table-hover">
  <thead>
    <tr>
      <th class="text-center" scope="col">
        <%= sort_link(@ransack, :comments_count, "Replied count", default_order: :desc) %>
      </th>
      <th scope="col">Title</th>
      <th class="text-center" scope="col"><%= sort_link(@ransack, :comments_created_at, "Last replied at", default_order: :desc) %></th>
      <th class="text-center" scope="col"><%= sort_link(@ransack, :viewed_count, "Viewed count", default_order: :desc) %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <% if post.who_can_see == "All" ||
        current_user != nil &&
        post.who_can_see == "Friend" && current_user.friend?(post.user) == "friend" ||
         post.user == current_user %>
        <tr data-link="<%= post_path(post.id) %>">
          <th class="text-center"><%= post.comments_count %></th>
          <td><%= post.title %></td>
          <td class="text-center">
            <% if post.comments_count != 0 %>
              <%= post.comments.last.created_at.strftime("%Y-%m-%d") %>
            <% end %>
          </td>
          <td class="text-center"><%= fa_icon "eye", text:  post.viewed_count %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<script>
  $("tr[data-link]").click(function() {
    window.location = $(this).data("link")
  })
</script>

app/views/shared/_user_content.html.erb
<div class="row">
  <div class="col-3">
    <%= filestack_image @user.avatar, transform: filestack_transform.resize(width:150, height:150) if @user.avatar && @user.avatar != "" %>

    <h4><%= @user.name %></h4>

    <div class="text-center">
      <%= render partial: "shared/friendship_button" %>
    </div>
  </div>

  <div class="col-9">
    <h5><%= @user.introduction %></h5>

    <br>
    <span  class="float-right">
      <% if current_user == @user %>
        <%= link_to edit_user_path(@user.id), class:"btn btn-primary" do %>
          <%= fa_icon "edit 2x" %>
        <% end %>
      <% end %>
    </span>
  </div>
</div>

app/views/shared/_user_nav_tabs.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="nav-item">
    <%= link_to "My Post", user_path(@user.id), class: "nav-link #{ 'active' if current_page?(user_path(@user.id)) }" %>
  </li>
  <li class="nav-item">
    <%= link_to "My Comment", comment_user_path(@user.id), class: "nav-link #{ 'active' if current_page?(comment_user_path(@user.id)) }" %>
  </li>

  <li class="nav-item">
    <%= link_to "My Collect", collect_user_path(@user.id), class: "nav-link #{ 'active' if current_page?(collect_user_path(@user.id)) }" %>
  </li>

  <% if current_user == @user %>
    <li class="nav-item">
      <%= link_to "My Draft", draft_user_path(@user.id), class: "nav-link #{ 'active' if current_page?(draft_user_path(@user.id)) }" %>
    </li>
  <% end %>

  <li class="nav-item">
    <%= link_to "My Friend", friend_user_path(@user.id), class: "nav-link #{ 'active' if current_page?(friend_user_path(@user.id)) }" %>
  </li>
</ul>

app/views/shared/_user_post.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col-md-auto">Title</th>
      <th scope="col">Status</th>
      <th scope="col">Created at</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post.id) %></td>
        <th class="text-capitalize"><%= post.status %></th>
        <td><%= post.created_at.strftime("%Y-%m-%d") %></td>
        <td>
          <%= render partial: "shared/post_button", locals: {post: post} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>