config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ## 前台路由
  # root
  root "posts#index"

  # 使用者
  resources :users, only: [:edit, :update, :show] do
    member do
      get :draft
      get :comment
      get :collect
      get :friend

      # 好友關係
      post :friend_request
      post :friend_accept
      post :friend_ignore
    end
  end

  # 文章
  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]

    # 文章收藏記錄
    member do
      post :collect
      delete :uncollect
    end
  end

  # posts#index 的文章分類按鈕
  resources :categories, only: [:show]

  ## 後台路由
  # 進入後台必須有管理員 (admin) 權限
  namespace :admin do
    # GET /admin/users  後台可以瀏覽所有使用者清單
    # POST  /admin/:id/user   可以更新使用者的身份
    resources :users, only: [:index, :update]
    # 後台可以 CRUD `文章的分類` (但不能刪除已經有被使用的分類)
    resources :categories

    # 後台首頁
    root "users#index"
  end

  # API路由
  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, except: [:edit]
    end
  end

  # Feeds
  resources :feeds, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum App Practice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= filestack_js_include_tag %>
    <%= filestack_js_init_tag %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <%= link_to "Forum App Practice", root_path, class:"navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item nav-link"><%= link_to "Feeds", feeds_path, class: "nav-link" %></li>
          <li class="nav-item nav-link"><%= link_to "All Post", root_path, class: "nav-link" %></li>
          <li class="nav-item nav-link"><%= link_to('New Post', new_post_path, class: "nav-link") %></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
            <span class="navbar-text"><%= current_user.email %></span>

            <% if current_user.is_admin? %>
              <li class="nav-item"><%= link_to "(Admin)", admin_root_path, class: "nav-link" %></li>
            <% end %>

            <li class="nav-item"><%= link_to('Porfile', user_path(current_user), class: "nav-link") %></li>
            <li class="nav-item"><%= link_to('Account Setting', edit_user_registration_path, class: "nav-link") %></li>
            <li class="nav-item"><%= link_to('Log out', destroy_user_session_path, method: :delete, class: "nav-link") %></li>
          <% else %>
            <li class="nav-item"><%= link_to('Sign in', new_user_registration_path, class: "nav-link") %></li>
            <li class="nav-item"><%= link_to('Log in', new_user_session_path, class: "nav-link") %></li>

          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
          <% if flash[:notice] %>
            <div class="alert alert-success alert-dismissible fade show text-center" role="alert">

              <%= notice %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div >
          <% end %>

          <% if flash[:alert] %>
          <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">

            <%= alert %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div >
          <% end %>
        </div>

    <%= yield %>
  </body>